name: change_detector
description: Detects if a Dart library needs a major or minor version bump.
# version: 1.0.0

environment:
  sdk: '>3.0.0 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.9
dependencies:
  analyzer: 8.1.0
  args: ^2.7.0
  path: ^1.9.1
